# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf7991a1592c15d9e5d343b4f64147b9c66af93be93a19da2304c8e0bd3061822b08238f010478c721762ba18d8eebd3f331f998ead1e587c5c761d62a43e25e

test:
  secret_key_base: 63ae15a185dcc6bb48c933d1d28abe155c10df38e7313e211559cc6722dd12344ccce3cfbdb397400ec2df0d9ac11144d4ceecaec88907512bc22914b329bcf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
